name: Project RING! - Frontend CI/CD flow

on:
  push:
    branches: [main]
    paths:
      - "front-end/**"
      - ".github/workflows/front-end.yaml"

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: front-end/package-lock.json

      - name: Install Dependencies
        working-directory: front-end
        run: npm ci

      - name: Run tests
        working-directory: front-end
        run: npm run test

      - name: Build
        working-directory: front-end
        run: npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: front-end/apps/web/dist

  deploy:
    name: Deploy Cloudflare
    needs: [build-test]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: front-end/apps/web/dist

      - name: Deploy Bookstore App
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy front-end/apps/web/dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
